org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=false

# Versioni Minecraft / Fabric
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.1

# Info mod
mod_version=1.0.0
maven_group=com.a353bit.mobesp
archives_base_name=mobesp

# Dipendenze
fabric_version=0.135.0+1.21.10
